version: '3'
services:
  db:
    image: mysql:5.7
    volumes:
      - ./persist/mysql:/var/lib/mysql
    restart: always
    command: mysqld --sql_mode=""
    environment:
      MYSQL_ROOT_PASSWORD: iris
      MYSQL_DATABASE: iris
      MYSQL_USER: iris
      MYSQL_PASSWORD: iris
    networks:
      - iris_net

  iris-api:
    depends_on:
      - db
    #build: ./iris-api
    image: quay.io/iris/iris
    ports:
      - '16649:16649'
    restart: always
    environment:
      # This makes iris-api initialize the db schema upon first run
      DOCKER_DB_BOOTSTRAP: 'true'
    volumes:
      - ./config/iris-api:/home/iris/config
      - ./logs/iris-api/nginx:/home/iris/var/log/nginx
      - ./logs/iris-api/uwsgi:/home/iris/var/log/uwsgi
    networks:
      - iris_net

  iris-relay:
    depends_on:
      - iris-api
      - db
    image: quay.io/iris/iris-relay
    ports:
      - '16648:16648'
    restart: always
    environment:
      # This makes iris-relay initialize the db schema upon first run
      DOCKER_DB_BOOTSTRAP: 'true'
    volumes:
      - ./config/iris-relay:/home/iris-relay/config
      - ./logs/iris-relay/nginx:/home/iris-relay/var/log/nginx
      - ./logs/iris-relay/uwsgi:/home/iris-relay/var/log/uwsgi
    networks:
      - iris_net

  prometheus:
    image: prom/prometheus
    volumes:
      - ./persist/prometheus:/prometheus-data
      - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - iris-api
    restart: always
    ports:
      - 9090:9090
    networks:
      - iris_net

networks:
  iris_net:
    driver: bridge
